- name: check java installed
  fail:
    msg: "$JAVA_HOME isn't set"
  when: lookup('env', 'JAVA_HOME') == ''

- name: install maven
  unarchive:
    src: http://ftp.heanet.ie/mirrors/www.apache.org/dist/maven/maven-{{ maven_version|regex_replace('\.\w+\.\w+$', '') }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    dest: /opt
    remote_src: true
  
- name: add mvn to PATH
  template:
    src: set_path.sh
    dest: /etc/profile.d
    mode: "0644"
    backup: yes



